exec { 'apt-get-update': 
    command => '/usr/bin/apt-get update',
}
Package { ensure => "latest",
		require=>Exec['apt-get-update']}
$honeydew= [
# needed
"nginx",
# not_needed 
"git"]
package {$honeydew:}

service {"nginx":
	enable =>true,
	ensure =>"running",
	require=>Exec['nginx_config']}

file {"/etc/nginx/nginx.conf",
	 ensure=>"present",
	 #as a string
	 #or from a template
	 source=>"/etc/conf/nginx.conf"
	 }
git clone --mirror https://github.com/puppetlabs/exercise-webpage.git

	 https://github.com/puppetlabs/exercise-webpage/blob/master/index.html